api/urls.py
from django.conf.urls import include, url
from tastypie.api import Api

from .resources import UfResource
from .resources import MunicipioResource

v1_api = Api(api_name='v1')
v1_api.register(UfResource())
v1_api.register(MunicipioResource())

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

axis/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_views
from . import views
from .forms import PasswordResetForm

urlpatterns = [
    url(r'^cadastro/$', views.user_create, name='user_add'),
    url(r'^profile/edit/$', views.profile_form, name='profile_edit'),
    url(r'^profile/detail/$', views.profile_detail, name='profile_detail'),
    url(r'^profile/detail/(?P<pk>\d+)/$', views.profile_detail, name='profile_detail'),
    url(r'^cadastro/confirmacao/(?P<uid>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', views.user_email_verification_confirm, name='email_verification_confirm'),
    url(r'^cadastro/reenviar-email-confirmacao/$', views.user_email_verification_resend, name='email_verification_resend'),

    url(r'^(?P<pk>\d+)/rede_social/cadastro/$', views.rede_social_create, name='rede_social_core_create'),
    url(r'^(?P<pk>\d+)/rede_social/(?P<rede_social_pk>\d+)/$', views.rede_social_update, name='rede_social_core_update'),

    url(r'^lista_pessoa_fisica.geojson$', views.lista_pessoa_fisica, name='lista_pessoa_fisica'),

    url(
        r'^galeria/list/app/(?P<src_app>\w+)/model/(?P<src_model>\w+)/(?P<src_pk>\d+)/$',
        views.galeria_list,
        name='galeria_list'
    ),
    url(
        r'^galeria/dashboard/app/(?P<src_app>\w+)/model/(?P<src_model>\w+)/(?P<src_pk>\d+)/$',
        views.galeria_dashboard,
        name='galeria_dashboard'
    ),

    url(
        r'^galeria/counter/app/(?P<src_app>\w+)/model/(?P<src_model>\w+)/(?P<src_pk>\d+)/$',
        views.galeria_counter,
        name='galeria_counter'
    ),

    url(
        r'^galeria/form/app/(?P<src_app>\w+)/model/(?P<src_model>\w+)/(?P<src_pk>\d+)/create/$',
        views.galeria_create,
        name='galeria_create'
    ),

    url(
        r'^galeria/form/app/(?P<src_app>\w+)/model/(?P<src_model>\w+)/(?P<src_pk>\d+)/update/(?P<pk>\d+)/$',
        views.galeria_update,
        name='galeria_update'
    ),

    # password reset views

    url(
        r'^cadastro/senha/reset/$',
        django_views.password_reset,
        {
            'post_reset_redirect': '/usuario/cadastro/senha/reset/done/',
            'email_template_name': 'registration/email/password_reset_email.html',
            'password_reset_form': PasswordResetForm
        },
        name='password_reset'
    ),
    url(
        r'^cadastro/senha/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
        django_views.password_reset_confirm,
        {
            'post_reset_redirect': '/usuario/cadastro/senha/done/'
        },
        name='password_reset_confirm'
    ),
    url(
        r'^cadastro/senha/reset/done/$',
        django_views.password_reset_done,
        name='password_reset_done'
    ),
    url(
        r'^cadastro/senha/done/$',
        django_views.password_reset_complete,
        name='password_reset_complete'
    ),
]

axis/core/models.py
# -*- coding: utf-8 -*-

import os
from PIL import ImageOps
from PIL.ExifTags import TAGS
from cStringIO import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile

from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)
from django.db.models import Case, When, Q, Value
from django.apps import apps
from django.contrib.gis.db import models
from django.contrib.sites.models import Site
from django.core.files.storage import get_storage_class
from django.core.urlresolvers import reverse_lazy, reverse
from django.template.loader import get_template
from django.utils import timezone
from django.utils.deconstruct import deconstructible
from django.utils.http import int_to_base36
from municipios.models import Municipio
from utils import equipamentos_entorno
from uuid import uuid4

from PIL import Image


avatar_storage = get_storage_class(settings.DEFAULT_FILE_STORAGE)()


@deconstructible
class UploadToPathAndRename(object):

    def __init__(self, path):
        self.sub_path = path

    def __call__(self, instance, filename):
        ext = filename.split('.')[-1]
        filename = '{}.{}'.format(uuid4().hex, ext)
        return os.path.join(self.sub_path, filename)


class Endereco(models.Model):
    '''
    Modelo ZNC / NECTO padrão para endereço.
    Depende do app  django-municipios.
    **IMPORTANTE** -> personalizar o Manager na classe filha para GeoManager.

    Attributes:

        CEP(string):  gravado sem traço. (sp começa com 0 (zero))
        municipio(integer): refere-se a Código do IBGE,
                            depende da app django-municipios
                            (projeto opensource da ZNC/Necto)
        point(geom Point):

    '''

    cep = models.CharField(max_length=8)  # 12232060
    logradouro = models.CharField(max_length=100)
    numero = models.CharField(verbose_name=u'Número', max_length=50)
    complemento = models.CharField(max_length=100, null=True, blank=True)
    bairro = models.CharField(max_length=100)
    municipio = models.ForeignKey(Municipio)  # como código do IBGE
    point = models.PointField(srid=settings.SRID, null=True, blank=True)

    def __unicode__(self):
        return u"%s - %s" % (self.get_cep(), self.numero)

    @property
    def endereco(self):
        res = [self.logradouro or u'']
        if self.numero:
            res.append(self.numero or u'')
        if self.cep:
            res.append(u'CEP: {}'.format(self.get_cep()))

        return u' - '.join(res)

    def get_cep(self):
        cep_mascarado = self.cep[0:5] + "-" + self.cep[5:]
        return cep_mascarado

    class Meta:
        abstract = True


SEXO_CHOICES = (
    ('M', u'Masculino'),
    ('F', u'Feminino')
)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('O email é obrigatório')
        email = UserManager.normalize_email(email)
        user = self.model(email=email, is_active=True, is_superuser=False,
                          last_login=now, date_joined=now, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        user = self.create_user(email, password, **extra_fields)
        user.is_active = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class ItemGaleria(models.Model):
    '''
    Se o item da galeria for do tipo audiovisual então trata-se de um link
    para um video no Youtube/Vimeo/Etc.

    Neste caso os campos preenchidos serão:
    - tipo == 1
    - descricao
    - titulo
    - data
    - local
    - url

    Se o item da galeria for do tipo imagem então trata-se de um arquivo
    visual, salvo no sistema de arquivos.

    Neste caso os campos preenchidos serão:
    - tipo == 2
    - descricao
    - titulo
    - data
    - local
    - arquivo
    - thumbnail         <-- automático

    Se o item da galeria for do tipo documento então trata-se de um arquivo
    não-visual, salvo no sistema de arquivos.

    Neste caso os campos preenchidos serão:
    - tipo == 3
    - descricao
    - titulo
    - data
    - local
    - arquivo
    '''
    class TIPO:
        AUDIOVISUAL = 1
        IMAGEM = 2
        DOCUMENTO = 3
        CHOICES = (
            (AUDIOVISUAL, u'Áudiovisual'),
            (IMAGEM, u'Imagem'),
            (DOCUMENTO, u'Documento'),
        )

    arquivo = models.FileField(
        u'Arquivo',
        upload_to='galeria',
        null=True, blank=True,
    )

    descricao = models.TextField(u'Descrição', null=False, blank=False)
    titulo = models.CharField(u'Título', null=False,
                              blank=False, max_length=100)
    data = models.DateField(u'Data', null=True, blank=True)
    local = models.CharField(u'Local', max_length=150, null=True, blank=True)
    tipo = models.SmallIntegerField(
        u'Tipo de arquivo', null=False, blank=True, choices=TIPO.CHOICES)
    url = models.CharField(u'URL', max_length=255, null=True, blank=True)
    thumbnail = models.FileField(
        u'Thumbnail',
        upload_to='galeria',
        null=True, blank=True,
    )

    def create_thumbnail(self):
        if self.tipo != ItemGaleria.TIPO.IMAGEM:
            return

        fileName, fileExtension = os.path.splitext(self.arquivo.path)

        if fileExtension.lower() == '.jpg' or fileExtension.lower() == '.jpeg':
            DJANGO_TYPE = 'image/jpeg'
        elif fileExtension.lower() == '.png':
            DJANGO_TYPE = 'image/png'
        else:
            return

        if DJANGO_TYPE == 'image/jpeg':
            PIL_TYPE = 'jpeg'
            FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
            PIL_TYPE = 'png'
            FILE_EXTENSION = 'png'

        image = Image.open(StringIO(self.arquivo.read()))

        if FILE_EXTENSION == 'jpg':
            exif = image._getexif()
            if exif is not None:
                for tag, value in exif.items():
                    decoded = TAGS.get(tag, tag)
                    if decoded == 'Orientation':
                        if value == 3:
                            image = image.rotate(180)
                        if value == 6:
                            image = image.rotate(270)
                        if value == 8:
                            image = image.rotate(90)
                        break

        image.save(self.arquivo.path, overwrite=True)

        thumb = ImageOps.fit(
            image.copy(),
            (120, 120,),
            Image.ANTIALIAS,
            0,
            (0.5, 0.5)
        )

        # Save the thumbnail
        temp_handle = StringIO()
        thumb.save(temp_handle, PIL_TYPE, quality=100)
        temp_handle.seek(0)

        # Save image to a SimpleUploadedFile which can be saved into
        # ImageField
        suf = SimpleUploadedFile(
            os.path.split(self.arquivo.name)[-1],
            temp_handle.read(),
            content_type=DJANGO_TYPE
        )

        # Save SimpleUploadedFile into image field
        self.thumbnail.save(
            '{0}_thumbnail_{1}_120x120.png'.format(
                os.path.splitext(self._smart_str(suf.name))[0],
                FILE_EXTENSION
            ),
            suf,
            save=False
        )

    def _smart_str(self, text):
        if isinstance(text, unicode):
            return unicode(text).encode("utf-8")
        elif isinstance(text, int) or isinstance(text, float):
            return str(text)
        return text

    def video_data_type(self):
        if self.tipo != ItemGaleria.TIPO.AUDIOVISUAL:
            return

        if 'vimeo' in self.url:
            return 'vimeo'
        elif 'youtube' in self.url:
            return 'youtube'
        else:
            return 'unsupported'

    def video_data_videoid(self):
        if self.tipo != ItemGaleria.TIPO.AUDIOVISUAL:
            return

        if 'vimeo' in self.url:
            return self.url.replace('https://vimeo.com/', '')
        elif 'youtube' in self.url:
            return self.url.replace('https://www.youtube.com/watch?v=', '')
        else:
            return 'unsupported'

    def full_description(self):
        meta_list = []
        if self.data:
            meta_list.append(self.data.strftime("%d/%m/%Y"))

        if self.local:
            meta_list.append(self.local)

        if meta_list:
            meta_data = '[%s]' % (
                ' - '.join(meta_list)
            )
        else:
            meta_data = ''

        return '%s %s' % (
            self.titulo,
            meta_data
        )

    class Meta:
        verbose_name = u'Item de Galeria'
        verbose_name_plural = u'Itens de Galeria'
        ordering = ('pk', )

    def __unicode__(self):
        return self.get_tipo_display()


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('e-mail', unique=True)

    nome = models.CharField(
        verbose_name=u'Nome ou nome social', max_length=100)

    is_active = models.BooleanField('ativo', default=False,)
    is_email_verified = models.BooleanField(
        'E-mail verificado', default=False,)
    is_staff = models.BooleanField('administrador', default=False,)
    date_joined = models.DateTimeField(
        'data de cadastro', default=timezone.now)

    last_emailverification = models.DateTimeField(default=timezone.now)

    galeria = models.ManyToManyField(ItemGaleria)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('nome', )

    class Meta:
        verbose_name = u'Usuário'
        verbose_name_plural = u'Usuários'
        ordering = ('nome', 'email')

    @property
    def tipo(self):
        return u'Agente Pessoa Física'

    @property
    def projetos(self):
        '''

axis/core/templates/core/profile_form.html
{% extends 'base.html' %}
{% load l10n static foundation_filter %}

{% block extra_head %}
<meta name="description" content="Adicione detalhes ao seu perfil no CulturaEduca. Participe da construção coletiva do mapa de educação
e cultura no Brasil.">
{% endblock %}

{% block titulo %} Cadastro de usuário {% endblock titulo %}

{% block extra_css %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/openlayers/3.17.1/ol.css" type="text/css">

{{ form.media.css }}
{% endblock extra_css %}

{% block content %}
<div class="content-page">
    <div class="title">
        <div class="row">
            Perfil do usuário: {{user.nome}}
        </div>
    </div>
<div class="row">
    <div data-alert class="alert-box warning radius">
        <button tabindex="0" class="close" aria-label="Close Alert">&times;</button>
        <h5>Orientações gerais:</h5>
        <ol>
            <li>Os campos com <i class="fa fa-asterisk" style="font-size:8px;color:red;vertical-align:super;" aria-hidden="true"></i> são obrigatórios.</li>
            <li>Você pode escolher quais dados deseja deixar público, basta "mover o interruptor" para a esquerda: 
                <div class="switch tiny radius" style="display:inline;vertical-align:-2px;" >
                    <input id="exampleCheckboxSwitch" type="checkbox">
                    <label for="exampleCheckboxSwitch" ></label>
                </div> 
            </li>
            <li>Se tiver dúvidas ou quiser saber mais sobre alguma informação solicitada, clique em <span data-tooltip aria-haspopup="true" class="has-tip" title="Saiba Mais"><img src="{% static 'img/info3.png' %}" alt="info" /></a></span></li>
            <li>Você poderá editar esse perfil sempre que quiser.</li>
            <li>Veja o tutorial detalhado de preenchimento <a href="#">clicando aqui</a></li>
        </ol>

    </div>
    
        <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="columns medium-12">
                <fieldset>
                    <legend>Identificação</legend>

                    <div class="row">
                        <div class="medium-6 columns">{{ form.data_nascimento|as_fdt }}</div>
                        <div class="medium-6 columns">{{ form.identidade_genero|as_fdt }}</div>
                    </div>
                    <div class="row">
                        <div class="medium-12 columns">{{ form.avatar|as_fdt }}</div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="medium-6 columns ">{{ form.raca_cor_ibge|as_fdt }}</div>
                        <div class="medium-6 columns ">{{ form.etnia|as_fdt }}</div>
                    </div>
                    <div class="row">
                        <div class="medium-6 columns outro">{{ form.raca_cor_ibge_outro|as_fdt }}</div>
                        <div class="medium-6 columns outro">{{ form.etnia_outro|as_fdt }}</div>
                    </div>
                    <div class="row">
                        <div class="medium-6 columns">{{ form.ocupacao|as_fdt }}</div>
                        <div class="medium-6 columns">{{ form.escolaridade|as_fdt }}</div>
                    </div>
                    <div class="row">
                        <div class="medium-6 columns outro">{{ form.ocupacao_outro|as_fdt }}</div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Contato</legend>
                    <div class="row">
                        <div class="medium-6 columns">
                            <span class="data">
                                <label data-privacy-switch="true">E-Mail
                                    <div class="right">
                                        <div
                                        class="switch radius tiny has-tip tip-right"
                                        data-tooltip aria-haspopup="true"
                                        title="{% if user.get_privacy_objects.email.public %}<i class='fa fa-unlock' aria-hidden='true'></i> Público{% else %}<i class='fa fa-lock' aria-hidden='true'></i> Privado{% endif %}"
                                        style="border-bottom:none;">
                                        <input class="switch-input" id="id_email_privacy" type="checkbox" name="privacy_fields" value="{{ user.get_privacy_objects.email.pk }}"{% if user.get_privacy_objects.email.public %} checked{% endif %}>
                                        <label class="switch-paddle" for="id_email_privacy">
                                        </label>
                                    </div>
                                </div>
                            </label>
                            {{ user.email }}
                        </span>
                    </div>
                </div><br>

                <div class="row">
                    <div class="medium-6 columns"> {{ form.telefone1|as_fdt }}</div>
                    <div class="medium-6 columns"> {{ form.telefone2|as_fdt }}</div>
                </div>
                <fieldset>
                    <legend style="font-weight:normal">Redes Sociais</legend>
                    {{ redesocial_formset.management_form }}
                    <div class="row redesocial_row">
                        {% for form in redesocial_formset %}
                        <div class="wrapper">
                            <div class="medium-6 columns">
                                {{ form.non_field_errors }}
                                {{ form.errors }}
                                {{form.plataforma|as_fdt}}
                            </div>
                            <div class="medium-6 columns">
                                {{form.link|as_fdt}}
                            </div>
                            <div >
                                {{ form.id }}
                                {{ form.DELETE }}
                                {{ form.coletivo }}
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    <div class="row">
                        <div class="medium-12 columns">
                            <div class="right">
                                <a class="button radius tiny alert removeForm" data-formset="redesocial" title="Remover Rede Social"><i class="fa fa-close"></i></a>
                                <a class="button radius tiny addForm" data-formset="redesocial" title="Adicionar Rede Social"><i class="fa fa-plus"></i></a>
                            </div> 
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <fieldset style="position: relative;">
                <legend>Localização/Endereço</legend>
                <div data-alert class="alert-box warning radius">
                    ATENÇÃO: por padrão, o endereço das Pessoas Físicas não é público! Só você poderá ver seu ponto no mapa, para os demais usuários aparecerá apenas seu Município e UF. Você pode mudar essa configuração. A responsabilidade de divulgação do seu endereço pessoal será somente sua.
                </div>
                <div class="row">
                    <div class="right" style="margin-right: 20px;">
                        <div class="switch tiny radius has-tip tip-right"
                        data-tooltip aria-haspopup="true"
                        title="{% if user.get_privacy_objects.endereco.public %}<i class='fa fa-unlock' aria-hidden='true'></i> Público{% else %}<i class='fa fa-lock' aria-hidden='true'></i> Privado{% endif %}"
                        style="border-bottom: none;">
                            <input class="switch-input" id="id_endereco_privacy" type="checkbox" name="privacy_fields" value="{{ user.get_privacy_objects.endereco.pk }}"{% if user.get_privacy_objects.endereco.public %} checked{% endif %}>
                            <label class="switch-paddle" for="id_endereco_privacy"></label>
                        </div>
                    </div>
                </div>
            {% include "endereco_fieldset.html" %}
            </fieldset>
            <fieldset>
                <legend>Atuação</legend>
                <div class="row">
                    <div class="medium-6 columns">{{ form.area_atuacao|as_fdt }} </div>
                    <div class="medium-6 columns">{{ form.atua_desde|as_fdt }}</div>
                </div><br>
                <div class="row">
                    <div class="medium-6 columns outro">{{ form.area_atuacao_outro|as_fdt }}</div>
                </div></br>
                <div class="row">
                    <div class="medium-6 columns">{{ form.tipo_espaco|as_fdt }}</div>
                    <div class="medium-6 columns">{{ form.abrangencia|as_fdt }} </div>
                </div><br>
                <div class="row">
                    <div class="medium-6 columns outro">{{ form.tipo_espaco_outro|as_fdt }}</div>
                </div><br>
                <div class="row">
                    <div class="medium-6 columns">{{ form.publico_focal|as_fdt }}</div>
                    <div class="medium-6 columns">{{ form.area_pesquisa|as_fdt }} </div>
                    
                </div><br>
                
                <!-- <div class="row">
                    <div class="medium-6 columns">{{ form.linguagens_artisticas|as_fdt }} </div>
                    <div class="medium-6 columns">{{ form.manifestacao_cultural|as_fdt }} </div>
                </div><br>
                <div class="row">
                    <div class="medium-6 columns outro">{{ form.manifestacao_cultural_outro|as_fdt }}</div>
                </div><br> -->
                <div class="row">
                    <div class="medium-12 columns">{{ form.atuacao|as_fdt }} </div>
                </div>

            </fieldset>
        </div>
        <div class="row align-right">
            <div class="medium-6 columns">
                <a role="button" class="button small alert" href="/">Cancelar</a>
                <button role="button" class="button small success" type="submit"> Salvar</button>
            </div>
        </div>
    </form>

</div>

{% endblock content %}

{% block extra_js %}
{{ form.media.js }}
<script src="{% static 'js/form/formset.js' %}" type="text/javascript"></script>
<script src="{% static 'js/form/form_field_outros.js' %}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/3.17.1/ol.js" type="text/javascript"></script>
<script src="{% static 'js/map.js' %}?v=1" type="text/javascript"></script>


<!-- Map Init - Ol -->
<script type="text/javascript">
var initialPointWKT = "{{ form.instance.point.wkt|safe|default:'' }}";
</script>

<script src="{% static 'js/endereco_fieldset.js' %}?v=1.3" type="text/javascript"></script>

<script type="text/javascript">

$(function() {

    $('input[type="checkbox"].switch-input').change(function() {
        estado = "<i class='fa fa-lock' aria-hidden='true'></i> Privado";
        if (this.checked) {
            estado = "<i class='fa fa-unlock' aria-hidden='true'></i> Público";
        }
        var tooltip_selector = '#' + $(this).parents('div.switch').data('selector');
        var arrow = $('<span />').addClass('nub');
        $(tooltip_selector).html(estado).append(arrow);
    });

    initFormSets({prefixes:['redesocial']});

    $('div[data-href]').click(function() {
        window.location.href = $(this).data('href');
    });

});

// Mask : js/jquery.mask.js está no base.html
$('#id_cep').mask('00000-000');

</script>
{% endblock %}

axis/core/templates/core/redesocial_form.html
{% extends 'base.html' %}
{% load l10n %}

{% block titulo %}
{% if form.instance.pk %}
    Editar Rede Social: {{ form.instance.nome }}
{% else %}
    Novo Rede Social
{% endif %}
{% endblock titulo %}

{% load static %}

{% block extra_css %}
<style type="text/css">
    input[readonly], select[readonly], textarea[readonly] {
        background-color: #ddd !important;
        cursor: default;
        pointer-events: none;
    }
</style>
{% endblock %}

{% block content %}

<div class="columns medium-8 medium-cetered">
    <div class="content-page">
        <a href="{% url 'profile_detail' %}" class="btn">Usuário: {{ user }}</a>
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <caption>Rede Social</caption>
                <div class="row">
                   <div class="medium-12 columns"><label for="" >{{ form.plataforma.label_tag }} {{ form.plataforma }}</label></div>
                </div>
                <div class="row">
                   <div class="medium-12 columns"><label for="" >{{ form.link.label_tag }} {{ form.link }}</label></div>
                </div>
                <div class="row">
                   <div class="medium-12 columns"><label for="" >{{ form.nome.label_tag }} {{ form.nome }}</label></div>
                </div>
            </fieldset>
            <button class="btn" type="submit">Salvar</button>
        </form>
    </div>
</div>

{% endblock content %}

axis/core/templates/core/user_form.html
{% extends 'base.html' %}
{% load static foundation_filter %}

{% block titulo %} Cadastro de usuário {% endblock titulo %}

{% block extra_head %}
<meta name="description" content="Crie uma conta no CulturaEduca. Participe da construção coletiva do mapa de educação
e cultura no Brasil.">
{% endblock %}

{% block content %}
<div class="content-page">
	<div class="row">
		<p>&nbsp;</p>
		<div class="columns medium-centered medium-7">
			<div class="panel">
				<div class="columns medium-centered medium-10">
					<h3 class="text-center">Inicie seu cadastro</h3>
					<p>&nbsp;</p>
					<form method="post">{% csrf_token %}

						<div class="row">
							{{ form.nome|as_fdt }}
						</div>
						<div class="row">
							{{ form.email|as_fdt }}
						</div>
						<div class="row">
							{{ form.password1|as_fdt }}
						</div>
						<div class="row">
							{{ form.password2|as_fdt }}
						</div>
						<div class="row">
							<button type="submit" class="button radius expand">Cadastre-se</button>
						</div>

					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block extra_js %}{{ block.super }}
{% endblock extra_js %}