api/urls.py
from django.conf.urls import include, url
from tastypie.api import Api

from .resources import UfResource
from .resources import MunicipioResource

v1_api = Api(api_name='v1')
v1_api.register(UfResource())
v1_api.register(MunicipioResource())

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

axis/acao/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^projeto/cadastro/$', views.projeto_create, name='projeto_create'),
    url(r'^projeto/editar/(?P<pk>\d+)/$', views.projeto_update, name='projeto_update'),
    url(r'^projeto/(?P<pk>\d+)/$', views.projeto_detail, name='projeto_detail'),
    url(r'^projeto/(?P<projeto_pk>\d+)/atividade/cadastro/$', views.atividade_create, name='atividade_create'),
    url(r'^rede/projeto/$', views.projeto_list, name='projeto_list'),

    url(r'^atividade/cadastro/$', views.atividade_create, name='atividade_create'),
    url(r'^atividade/editar/(?P<pk>\d+)/$', views.atividade_update, name='atividade_update'),
    url(r'^atividade/(?P<pk>\d+)/$', views.atividade_detail, name='atividade_detail'),
    url(r'^rede/atividade/$', views.atividade_list, name='atividade_list'),

    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/$', views.acaolocal_manage_view, name='acaolocal_manage_view'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/cadastro$', views.local_create, name='acaolocal_create'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/editar/(?P<pk>\d+)/$', views.local_update, name='acaolocal_update'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/remover/(?P<pk>\d+)/$', views.local_remove, name='acaolocal_remove'),
    url(r'^(?P<tipo_acao>atividade|projeto)/(?P<acao_pk>\d+)/local/(?P<pk>\d+)/$', views.local_detail, name='acaolocal_detail'),
    url(r'^local/(?P<pk>\d+)/$', views.local_detail, name='acaolocal_detail'),
    url(r'^search-local/$', views.local_search, name='local_search'),

    url(r'^lista_projeto.geojson$', views.lista_projeto, name='lista_projeto'),
    url(r'^lista_atividade.geojson$', views.lista_atividade, name='lista_atividade'),
    url(r'^lista_acaolocal.geojson$', views.lista_acaolocal, name='lista_acaolocal'),

    url(r'^(?P<tipo>(adiciona|remove))-membro/(?P<pk>\d+)/me/$', views.acao_membership_add_remove_me, name='acao_membership_add_remove_me'),
    url(r'^adiciona-membro/(?P<pk>\d+)/$', views.acao_membership_add, name='acao_membership_add'),
    url(r'^(?P<tipo>(make|undo))-administrador/(?P<pk>\d+)/$', views.acao_membership_make_undo_admin, name='acao_membership_make_undo_admin'),

    url(r'^(?P<tipo>(adiciona|remove))-agente/(?P<acao_pk>\d+)/(?P<agente_pk>\d+)/$', views.acao_agente_vinculo_add_remove, name='acao_agente_vinculo_add_remove'),
]

axis/acao/models.py
# -*- coding: utf-8 -*-
from axis.core.models import (
    AreaAtuacao as Tema,
    Endereco as EnderecoBase,
    LinguagemArtistica,
    ManifestacaoCultural,
    PublicoFocal,
    UserAddUpd,
    ItemGaleria,
)
from django.conf import settings
# from django.core.files.storage import get_storage_class
from django.template.loader import get_template
from axis.agente.models import Agente
from django.contrib.gis.db import models
from django.contrib.gis.db.models.query import GeoQuerySet
from django.contrib.gis.geos import Point, MultiPoint, MultiPolygon
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse, reverse_lazy
from utils import equipamentos_entorno, clean_tilestache_cache
from django.db.models.signals import post_delete
from django.db.models import Case, When, Q, Value
# avatar_storage = get_storage_class(settings.DEFAULT_FILE_STORAGE)()


class Acao(UserAddUpd):
    ''' Ação (Projeto/Atividade) '''

    nome = models.CharField(u'Nome/Título', max_length=200)
    temas = models.ManyToManyField(Tema, verbose_name=u'Temas')  # AreaAtuacao
    temas_outro = models.CharField(
        verbose_name=u'Outro Tema', max_length=512, blank=True)
    publico_focal = models.ManyToManyField(
        PublicoFocal, verbose_name=u'Público Focal')
    publico_focal_outro = models.CharField(
        verbose_name=u'Outro Tipo de Público Focal', max_length=512, blank=True)
    linguagem_artistica = models.ManyToManyField(
        LinguagemArtistica, verbose_name=u'Linguagens Artísticas', blank=True)
    manifestacao_cultural = models.ManyToManyField(
        ManifestacaoCultural, verbose_name=u'Manifestações Culturais', blank=True)
    manifestacao_cultural_outro = models.CharField(
        verbose_name=u'Outro Tipo de Manifestação Cultural', max_length=512, null=True, blank=True)
    inicio = models.DateField(u'Data início da ação', null=True, blank=True)
    fim = models.DateField(u'Data fim da ação', null=True, blank=True)
    financiado = models.BooleanField(
        u'Financiado', help_text=u'Ação é financiada?')
    agente = models.ForeignKey(
        Agente, verbose_name=u'Agente', null=True, blank=True, related_name=u'acoes')
    locais = models.ManyToManyField('Local', through='LocalAcao')

    galeria = models.ManyToManyField(ItemGaleria)

    def __unicode__(self):
        return self.nome

    def get_child(self):
        for tipo in [u'atividade', u'projeto', ]:
            try:
                child = getattr(self, tipo)
                return child
            except AttributeError:
                pass

    def can_edit(self, user):
        if user.is_anonymous():
            return False

        # o usuário poderá editar a ação se for o agente que cadastrou ou se for admin do agente que cadastrou
        agentes = user.agentemembro_set.filter(
            is_administrador=True).values_list('agente__pk', flat=True)
        return self.user_add_id == user.id or self.agente_id in agentes

    def get_create_url(self):
        return self.__class__._get_create_url()

    @property
    def tipo(self):
        return self.get_child().__class__._tipo()

    @property
    def app_model(self):
        return 'acao.{}'.format(self.get_child().__class__.__name__)

    @property
    def agente_add(self):
        return self.agente if self.agente else self.user_add

    def is_member(self, user):
        return not user.is_anonymous() and self.membros_ativos().filter(user=user).count() >= 1

    def is_administrador(self, user):
        return not user.is_anonymous() and self.membros_ativos().filter(user=user, is_administrador=True).count() >= 1

    def can_change_gallery(self, user):
        return any([self.is_member(user), self.is_administrador(user)])

    def add_member(self, user, is_administrador=False, user_add=None, **kwargs):
        acaomembro = AcaoMembro(
            user=user, is_administrador=is_administrador, **kwargs)

        if user_add:
            acaomembro.user_add = user_add
            acaomembro.user_upd = user_add
        else:
            acaomembro.user_add = user
            acaomembro.user_upd = user

        self.acaomembro_set.add(acaomembro, bulk=False)

    def remove_member(self, user):
        if self.acaomembro_set.filter(is_administrador=True).exclude(user=user).count() >= 1:
            self.acaomembro_set.filter(user=user).delete()

    def add_vinculo(self, agente, user_add):
        vinculo = AcaoAgenteVinculo(
            agente=agente, user_add=user_add, user_upd=user_add)
        self.acaoagentevinculo_set.add(vinculo, bulk=False)

        return True

    def remove_vinculo(self, agente):
        self.acaoagentevinculo_set.filter(agente=agente).delete()

    def has_vinculo(self, agente):
        return self.acaoagentevinculo_set.filter(agente=agente).count() >= 1

    def membros_ativos(self):
        return self.acaomembro_set.filter(user__is_active=True)

    def send_new_member_email(self, user):
        from django.core.mail import send_mail

        current_site = Site.objects.get_current()
        subject = u'[Cultura Educa] - Novo membro em ação %s' % self.nome
        template = get_template('acao/email/email_novo_acaomembro.html')

        email = template.render({
            'site_name': current_site.name,
            'domain': current_site.domain,
            'protocol': u'https',
            'acao': self.get_child(),
            'user': user,
        })

        send_emails = self.acaomembro_set.filter(
            is_administrador=True).values_list('user__email', flat=True)

        return send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, send_emails, html_message=email)

    @property
    def locais_acoes(self):
        if not hasattr(self, '_locais'):
            locais_diretos_pk = list(
                self.locais_diretos.values_list('pk', flat=True))
            locais_atividades_pk = []
            if hasattr(self, 'atividades'):
                for atividade in self.atividades.all():
                    locais_atividades_pk.extend(
                        atividade.locais_diretos.filter(
                            local__point__isnull=False
                        ).values_list('pk', flat=True)
                    )
            locais_pks = set(locais_diretos_pk + locais_atividades_pk)
            setattr(self, '_locais', Local.objects.filter(
                locais_acoes__pk__in=locais_pks))
        return getattr(self, '_locais')

    @property
    def transformed_locais(self):
        """Transforma ponto para o SRID do mapa, utilizado na aba rede."""
        locais = self.locais_acoes
        locais.transform(3857)
        return locais

    def setores_censitarios_entorno(self, raio=1):
        if not hasattr(self, '_setores_censitarios_entorno'):
            from itertools import chain
            from ibge.models import SetorCensitario
            setores_pk = list(chain(*[
                SetorCensitario.objects.entorno(
                    local.point.y, local.point.x, raio
                ).values_list('pk', flat=True) for local in self.locais_acoes.filter(point__isnull=False)
            ]))
            setattr(self, '_setores_censitarios_entorno',
                    SetorCensitario.objects.filter(pk__in=set(setores_pk)))

        return getattr(self, '_setores_censitarios_entorno')

    @property
    def locais_multipoint(self):
        return MultiPoint(
            *self.locais_acoes.transform(srid_out=3857, geom_field='point').values_list('point', flat=True)
        )

    @property
    def setores_censitarios_entorno_polygon(self):
        from django.contrib.gis.db.models import Union
        return self.setores_censitarios_entorno().transform(
            srid_out=3857,
            geom_field='point'
        ).aggregate(area=Union('geom'))['area']

    @property
    def agentes(self):
        pks = self.acaoagentevinculo_set.values_list('agente__pk', flat=True)
        return Agente.objects.filter(pk__in=pks)

    @property
    def rede_acoes(self):
        pks = list(self.acaoagentevinculo_set.values_list(
            'agente__pk', flat=True))
        return Acao.objects.filter(agente__pk__in=pks).annotate(
            acao_outro_agente=Case(
                When(Q(agente__pk__in=pks), then=Value(True)),
                default=Value(False),
                distinct=True,
                output_field=models.BooleanField()
            )
        )

    @property
    def rede_projetos(self):
        return self.rede_acoes.filter(projeto__isnull=False)

    @property
    def rede_atividades(self):
        return self.rede_acoes.filter(atividade__isnull=False)


class Local(EnderecoBase):
    local_nome = models.CharField(
        u'Local',
        max_length=120,
        null=True,
        blank=True
    )
    objects = models.GeoManager()

    def __unicode__(self):
        return u'%s' % (
            self.local_nome if self.local_nome else u'Local #%s' % self.pk
        )

    def get_absolute_url(self):
        return reverse('acaolocal_detail', args=(self.pk,))

    @property
    def local(self):
        return u'%s' % self.local_nome

    @property
    def lista_url(self):
        return reverse_lazy('lista_acaolocal')

    def get_search_url(self):
        return reverse('local_search')

    @property
    def target_url(self):
        return self.get_absolute_url()

    def equipamentos_entorno(self, raio=1):
        return equipamentos_entorno(self, raio=raio, geom_field='point')


class LocalAcao(models.Model):
    acao = models.ForeignKey(Acao, related_name=u'locais_diretos')
    local = models.ForeignKey(Local, related_name=u'locais_acoes')

    def user_can_delete(self, user):
        return self.acao.can_edit(user)


def localacao_postdelete_signal(sender, instance, **kwargs):
    layer_name = u'acao_atividade' if isinstance(
        instance.acao.get_child(), Atividade) else u'acao_projeto'
    clean_tilestache_cache(point=instance.local.point, layer=layer_name)

axis/acao/templates/acaolocal_form.html
{% extends 'base.html' %}
{% load l10n staticfiles foundation_filter %}

{% block titulo %} {{ acao.tipo }} - Locais {% endblock titulo %}

{% block content %}
<div class="columns medium-12 medium-centered">
   <div class="content-page">

       {% if form.instance.pk %}
       <h2><small>Editar local:</small></h2>
       {% else %}
       <h2><small>Novo local para {{ acao.tipo }} <a href="{{ acao.get_absolute_url }}">{{ acao.nome }} </a></small></h2>
       {% endif %}

       <form id="endereco_fieldset_form" enctype="multipart/form-data" method="POST">{% csrf_token %}
        <div class="columns medium-12">
          <fieldset>
            <h5>Endereço</h5>
            <div class="row">
              <div class="medium-12 columns">
                {{ form.local_nome|as_fdt }}

                <ul id="drop_local_nome" class="f-dropdown content large open f-open-dropdown" aria-hidden="false" style="position: relative;left: 0px;width: 100%;max-width: 100%;top: 0px;display: none;">
                  <h3>Sugestões de Locais: </h3>
                  <span id="close_drop_local_nome" style="cursor: pointer;position: absolute;right: 10px;top: 5px;font-size: 18px;">&times;</span>
                  <ul id="drop_local_nome_list" class="drop_list" style="margin-left: 0.25rem;">
                    <li class="empty">Nenhuma sugestão disponível</li>
                  </ul>
                </ul>
              </div>
            </div>
            {% include "endereco_fieldset.html" %}
          </fieldset>
        </div>
        <div class="row">
          <div class="medium-12 columns">
            <div class="right">
                <a class="button secondary" href="{{ acao.get_absolute_url }}" role="button">Cancelar</a>
                <button class="button success" role="button" style="color:#fff;" type="submit">
                  {% if form.instance %}
                    Salvar
                  {% else %}
                    Adicionar
                  {% endif %}
                </button>
            </div>
          </div>
        </div>
       </form>
  </div>
</div>
{% endblock content %}

{% block extra_css %}
  {{ form.media.css }}
{% endblock extra_css %}

{% block extra_js %}
  {{ form.media.js }}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/3.17.1/ol.js" type="text/javascript"></script>
  <script src="{% static 'js/map.js' %}?v=1" type="text/javascript"></script>

  <!-- Map Init - Ol -->
  <script type="text/javascript">
    var initialPointWKT = "{{ form.instance.point.wkt|safe|default:'' }}";
    var acao_pk = "{{ acao.pk }}";
  </script>

  <script src="{% static 'js/endereco_fieldset.js' %}?v=1.3" type="text/javascript"></script>
{% endblock extra_js %}

axis/acao/templates/atividade_form.html
{% extends 'acao/base_form.html' %}
{% load l10n staticfiles foundation_filter %}

{% block subtitle %}
{{ block.super }}
{% if projeto %}
do <a href="{{ projeto.get_absolute_url }}" class="noafter">projeto {{ projeto.nome }}</a>
{% endif %}
{% endblock subtitle %}

{% block extra_css %}
{{ form.media.css }}
<style type="text/css">
#financiamentos .wrapper {
	-webkit-box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	-moz-box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	margin: 10px 0.9375rem;
	padding-left: 0.9375rem;
	padding-right: 0.9375rem;
	border-bottom: 1px solid #E1E1E1;
	background: #F9F9F9;  
}

</style>
{% endblock extra_css %}
{% block form %}
<form enctype="multipart/form-data" method="POST">
	{% csrf_token %}
	<div class="columns medium-12">
		<fieldset>
			<h5>Identificação</h5>
			<div class="row">
				{% if projeto %}
				<div class="medium-6 columns">{{ form.nome|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">{{ form.projeto|as_fdt }}</div>
				{% else %}
				<div class="medium-6 columns">{{ form.nome|as_fdt }}</div>
				{% endif %}
				<div class="medium-3 columns" >{{ form.acaomembro_vinculo|as_fdt }}</div>
				<div class="medium-3 columns" >{{ form.acaomembro_vinculo_outro|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">{{ form.formato_tipo|as_fdt }}</div>
				<div class="medium-6 columns left">{{ form.formato_outro|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">{{ form.vinculo|as_fdt }}</div>
				<div class="medium-6 columns">{{ form.resumo|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">
					{{ form.valor|as_fdt }}
				</div>
				<div class="medium-6 columns">
					{{ form.objetivo|as_fdt }}
				</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">{{ form.descricao|as_fdt }}</div>
				<div class="medium-6 columns">{{ form.inicio|as_fdt }}</div>
				<div class="medium-6 columns">{{ form.fim|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-6 columns">{{ form.temas|as_fdt }} </div>
				<div class="medium-6 columns">{{ form.publico_focal|as_fdt }}</div>
			</div><br>
			<div class="row">
				<div class="medium-6 columns outro">{{ form.temas_outro|as_fdt }}</div>
				<div class="medium-6 columns outro">{{ form.publico_focal_outro|as_fdt }}</div>
			</div>
<!-- 			<div class="row">
				<div class="medium-6 columns">{{ form.manifestacao_cultural|as_fdt }}</div> 
				<div class="medium-6 columns">{{ form.linguagem_artistica|as_fdt }}</div>
			</div><br>
			<div class="row">
				<div class="medium-6 columns outro">{{ form.manifestacao_cultural_outro|as_fdt }}</div>
			</div><br> -->
			<div class="row" style="padding-top: 15px;">
				<div class="medium-2 columns">{{ form.financiado|as_fdt }}</div>
				<div class="medium-10 columns">
					<div class="left" id="financiamentos" style="display: none;width: 100%;">
						{{ financiamentoformset.management_form }}
						<div class="acaofinanciamento_row">
							{% for financiamentoform in financiamentoformset %}
							<div class="wrapper">
								<div class="row">
									{{ financiamentoform.tipo|as_fdt }}
								</div>
								<div class="row financiamento_outro" style="display: none;">
									{{ financiamentoform.outro|as_fdt }}
								</div>
								<div class="row financiamento_empresa" style="display: none;">
									{{ financiamentoform.empresa|as_fdt }}
								</div>
								<div >
									{{ financiamentoform.id }}
									{{ financiamentoform.DELETE }}
								</div>
							</div>
							{% endfor %}
						</div>
						<div class="row" style="height:20px;">
							<div class="right" style="margin-right: 0.9375rem;margin-top: 10px;">
								<a class="button round tiny alert removeForm" data-formset="acaofinanciamento" title="Remover Financiamento"><i class="fa fa-close"></i></a>
								<a class="button round tiny addForm" data-formset="acaofinanciamento" title="Adicionar Financiamento"><i class="fa fa-plus"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</fieldset>
	</div>
	<div class="row align-right">
		<div class="medium-6 medium-offset-6 columns" style="text-align:right;">
			<a class="button secondary" href="{# url 'atividade_detail' form.instance.pk  #}" role="button">Cancelar</a> 
			<button class="button success" role="button" style="color:#fff;" type="submit">Salvar</button>
		</div>
	</div>
</form>
{% endblock form %}
{% block extra_js %}
{{ form.media.js }}
{{ block.super }}
<script src="{% static 'js/form/formset.js' %}" type="text/javascript"></script>
<script type="text/javascript">
$(function() {
	initFormSets(
          //specify the model in lowercase to build the management variables of the formset extra forms
          {prefixes: ['acaofinanciamento']}
          );

	$("#id_formato_outro")
	.before('<i class="fa fa-asterisk fdt_required" style="" aria-hidden="true"></i>');

	$("#id_formato_tipo").change(function() {
		if ($(this).val() == '{{ FORMATO_OUTRO_VALUE }}') {
			$("#id_formato_outro").prop('required', true);
			$("#id_formato_outro").prop('disabled', false);
			$("#id_formato_outro")[0].focus();
		} else {
			$("#id_formato_outro").prop('required', false);
			$("#id_formato_outro").prop('disabled', true);
		}
	});

	$("#id_nome").focus();

	$("#id_formato_tipo").change();

      // FINACIAMENTO_OUTRO_VALUE
      // FINACIAMENTO_EMPRESA_VALUE

    });
</script>
{% endblock extra_js %}

axis/acao/templates/projeto_form.html
{% extends 'acao/base_form.html' %}
{% load l10n staticfiles foundation_filter %}

{% block extra_css %}
{{ form.media.css }}
<style type="text/css">
#financiamentos .wrapper {
	-webkit-box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	-moz-box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	box-shadow: 0px 2px 2px 0px rgba(0,0,0,0.1);
	margin: 10px 0.9375rem;
	padding-left: 0.9375rem;
	padding-right: 0.9375rem;
	border-bottom: 1px solid #E1E1E1;
	background: #F9F9F9;  
}

</style>
{% endblock extra_css %}
{% block form %}
<form enctype="multipart/form-data" method="POST">
	{% csrf_token %}
	<div class="columns medium-12">
		{{form.errors}}
		<fieldset>
			<h5>Identificação</h5>
			<div class="row">
				<div class="medium-6 columns">{{ form.nome|as_fdt }}</div>
				<div class="medium-3 columns" >{{ form.acaomembro_vinculo|as_fdt }}</div>
				<div class="medium-3 columns" >{{ form.acaomembro_vinculo_outro|as_fdt }}</div>
			</div>
			<div class="row">
				<div class="medium-3 columns">{{ form.propositor_tipo|as_fdt }}</div>
				<div id="propositor" class="medium-6 columns left">{{ form.propositor|as_fdt }}</div>
				<div id="propositor_outro" style="display: none;" class="medium-6 columns left">{{ form.propositor_outro|as_fdt }}</div>
				
			</div>
			<div class="row" style="padding-top: 15px;">
				<div class="medium-2 columns">{{ form.financiado|as_fdt }}</div>
				<div class="medium-10 columns">
					<div class="left" id="financiamentos" style="display: none;width: 100%;">
						{{ financiamentoformset.management_form }}
						<div class="acaofinanciamento_row">
							{% for financiamentoform in financiamentoformset %}
							<div class="wrapper">
								<div class="row">
									{{ financiamentoform.tipo|as_fdt }}
								</div>
								<div class="row financiamento_outro" style="display: none;">
									{{ financiamentoform.outro|as_fdt }}
								</div>
								<div class="row financiamento_empresa" style="display: none;">
									{{ financiamentoform.empresa|as_fdt }}
								</div>
								<div >
									{{ financiamentoform.id }}
									{{ financiamentoform.DELETE }}
								</div>
							</div>
							{% endfor %}
						</div>
						<div class="row" style="height:20px;">
							<div class="right" style="margin-right: 0.9375rem;margin-top: 10px;">
								<a class="button round tiny alert removeForm" data-formset="acaofinanciamento" title="Remover Financiamento"><i class="fa fa-close"></i></a>
								<a class="button round tiny addForm" data-formset="acaofinanciamento" title="Adicionar Financiamento"><i class="fa fa-plus"></i></a>
							</div>
						</div>
					</div>
				</div>
				</div>
				<div class="row">
					<div class="medium-6 columns">{{ form.vinculo|as_fdt }}</div>
					<div class="medium-6 columns">{{ form.resumo|as_fdt }}</div>
				</div>
				<div class="row">
					<div class="medium-6 columns column-adjust">
						{{ form.valor|as_fdt }}       
						<br>
						{{ form.inicio|as_fdt }}
						<br>
						{{ form.fim|as_fdt }}
					</div>
					<div class="medium-6 columns">
						{{ form.objetivo|as_fdt }}
					</div>
				</div>
				<div class="row">
					<div class="medium-6 columns">{{ form.temas|as_fdt }} </div>
					<div class="medium-6 columns">{{ form.publico_focal|as_fdt }}</div>
				</div><br>
				<div class="row">
					<div class="medium-6 columns outro">{{ form.temas_outro|as_fdt }}</div>
					<div class="medium-6 columns outro">{{ form.publico_focal_outro|as_fdt }}</div>
				</div>
<!-- 				<div class="row">
					<div class="medium-6 columns">{{ form.manifestacao_cultural|as_fdt }}</div> 
					<div class="medium-6 columns">{{ form.linguagem_artistica|as_fdt }}</div>
				</div><br>
				<div class="row">
					<div class="medium-6 columns outro">{{ form.manifestacao_cultural_outro|as_fdt }}</div>
				</div><br> -->
			</fieldset>
		</div>
		<div class="row align-right">
			<div class="medium-6 medium-offset-6 columns" style="text-align:right;">
				<a class="button secondary" href="/" role="button">Cancelar</a>
				<button class="button success" role="button" style="color:#fff;" type="submit">Salvar</button>
			</div>
		</div>
	</form>
	{% endblock form %}
	{% block extra_js %}
	{{ form.media.js }}
	{{ block.super }}
	<script src="{% static 'js/form/formset.js' %}" type="text/javascript"></script>
	<script type="text/javascript">
	$(function() {
		initFormSets(
          //specify the model in lowercase to build the management variables of the formset extra forms
          {prefixes: ['acaofinanciamento']}
          );

		$("#id_propositor_outro")
		.before('<i class="fa fa-asterisk fdt_required" style="" aria-hidden="true"></i>');

		$("#id_propositor_tipo").change(function() {
			if ($(this).val() == '{{ PROPOSITOR_OUTRO_VALUE }}') {
				$("#propositor_outro").slideDown('fast');
				$("#propositor").slideUp('fast');
				$("#id_propositor_outro")[0].focus();
				$("#id_propositor_outro").prop('required', true);
			} else if ($(this).val() == '{{ PROPOSITOR_ND_VALUE }}') {
				$("#id_propositor").val('Não declarado');
				$("#propositor_outro").slideUp('fast');
				$("#propositor").slideDown('fast');
				$("#id_propositor_outro").prop('required', false);
			} else {
				$("#id_propositor").val($("#id_propositor").data('agente'));
				$("#propositor_outro").slideUp('fast');
				$("#propositor").slideDown('fast');
				$("#id_propositor_outro").prop('required', false);
			}
		});

		$("#id_propositor_tipo").change();

		$("#id_nome").focus();

		$("form").on('submit', function (argument) {
			var money = $("#id_valor").val();
			if (money){
				money = parseFloat(money.replace('.', '').replace(',', '.'));
				$("#id_valor").val(money);
			}
		})

      // FINACIAMENTO_OUTRO_VALUE
      // FINACIAMENTO_EMPRESA_VALUE

    });
</script>
{% endblock extra_js %}