api/urls.py
from django.conf.urls import include, url
from tastypie.api import Api

from .resources import UfResource
from .resources import MunicipioResource

v1_api = Api(api_name='v1')
v1_api.register(UfResource())
v1_api.register(MunicipioResource())

urlpatterns = [
    url(r'^', include(v1_api.urls)),
]

axis/acao/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^projeto/cadastro/$', views.projeto_create, name='projeto_create'),
    url(r'^projeto/editar/(?P<pk>\d+)/$', views.projeto_update, name='projeto_update'),
    url(r'^projeto/(?P<pk>\d+)/$', views.projeto_detail, name='projeto_detail'),
    url(r'^projeto/(?P<projeto_pk>\d+)/atividade/cadastro/$', views.atividade_create, name='atividade_create'),
    url(r'^rede/projeto/$', views.projeto_list, name='projeto_list'),

    url(r'^atividade/cadastro/$', views.atividade_create, name='atividade_create'),
    url(r'^atividade/editar/(?P<pk>\d+)/$', views.atividade_update, name='atividade_update'),
    url(r'^atividade/(?P<pk>\d+)/$', views.atividade_detail, name='atividade_detail'),
    url(r'^rede/atividade/$', views.atividade_list, name='atividade_list'),

    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/$', views.acaolocal_manage_view, name='acaolocal_manage_view'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/cadastro$', views.local_create, name='acaolocal_create'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/editar/(?P<pk>\d+)/$', views.local_update, name='acaolocal_update'),
    url(r'^(?P<acao_pk>\d+)/gerenciar-locais/remover/(?P<pk>\d+)/$', views.local_remove, name='acaolocal_remove'),
    url(r'^(?P<tipo_acao>atividade|projeto)/(?P<acao_pk>\d+)/local/(?P<pk>\d+)/$', views.local_detail, name='acaolocal_detail'),
    url(r'^local/(?P<pk>\d+)/$', views.local_detail, name='acaolocal_detail'),
    url(r'^search-local/$', views.local_search, name='local_search'),

    url(r'^lista_projeto.geojson$', views.lista_projeto, name='lista_projeto'),
    url(r'^lista_atividade.geojson$', views.lista_atividade, name='lista_atividade'),
    url(r'^lista_acaolocal.geojson$', views.lista_acaolocal, name='lista_acaolocal'),

    url(r'^(?P<tipo>(adiciona|remove))-membro/(?P<pk>\d+)/me/$', views.acao_membership_add_remove_me, name='acao_membership_add_remove_me'),
    url(r'^adiciona-membro/(?P<pk>\d+)/$', views.acao_membership_add, name='acao_membership_add'),
    url(r'^(?P<tipo>(make|undo))-administrador/(?P<pk>\d+)/$', views.acao_membership_make_undo_admin, name='acao_membership_make_undo_admin'),

    url(r'^(?P<tipo>(adiciona|remove))-agente/(?P<acao_pk>\d+)/(?P<agente_pk>\d+)/$', views.acao_agente_vinculo_add_remove, name='acao_agente_vinculo_add_remove'),
]

axis/acao/models.py
# -*- coding: utf-8 -*-
from axis.core.models import (
    AreaAtuacao as Tema,
    Endereco as EnderecoBase,
    LinguagemArtistica,
    ManifestacaoCultural,
    PublicoFocal,
    UserAddUpd,
    ItemGaleria,
)
from django.conf import settings
# from django.core.files.storage import get_storage_class
from django.template.loader import get_template
from axis.agente.models import Agente
from django.contrib.gis.db import models
from django.contrib.gis.db.models.query import GeoQuerySet
from django.contrib.gis.geos import Point, MultiPoint, MultiPolygon
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse, reverse_lazy
from utils import equipamentos_entorno, clean_tilestache_cache
from django.db.models.signals import post_delete
from django.db.models import Case, When, Q, Value
# avatar_storage = get_storage_class(settings.DEFAULT_FILE_STORAGE)()


class Acao(UserAddUpd):
    ''' Ação (Projeto/Atividade) '''

    nome = models.CharField(u'Nome/Título', max_length=200)
    temas = models.ManyToManyField(Tema, verbose_name=u'Temas')  # AreaAtuacao
    temas_outro = models.CharField(
        verbose_name=u'Outro Tema', max_length=512, blank=True)
    publico_focal = models.ManyToManyField(
        PublicoFocal, verbose_name=u'Público Focal')
    publico_focal_outro = models.CharField(
        verbose_name=u'Outro Tipo de Público Focal', max_length=512, blank=True)
    linguagem_artistica = models.ManyToManyField(
        LinguagemArtistica, verbose_name=u'Linguagens Artísticas', blank=True)
    manifestacao_cultural = models.ManyToManyField(
        ManifestacaoCultural, verbose_name=u'Manifestações Culturais', blank=True)
    manifestacao_cultural_outro = models.CharField(
        verbose_name=u'Outro Tipo de Manifestação Cultural', max_length=512, null=True, blank=True)
    inicio = models.DateField(u'Data início da ação', null=True, blank=True)
    fim = models.DateField(u'Data fim da ação', null=True, blank=True)
    financiado = models.BooleanField(
        u'Financiado', help_text=u'Ação é financiada?')
    agente = models.ForeignKey(
        Agente, verbose_name=u'Agente', null=True, blank=True, related_name=u'acoes')
    locais = models.ManyToManyField('Local', through='LocalAcao')

    galeria = models.ManyToManyField(ItemGaleria)

    def __unicode__(self):
        return self.nome

    def get_child(self):
        for tipo in [u'atividade', u'projeto', ]:
            try:
                child = getattr(self, tipo)
                return child
            except AttributeError:
                pass

    def can_edit(self, user):
        if user.is_anonymous():
            return False

        # o usuário poderá editar a ação se for o agente que cadastrou ou se for admin do agente que cadastrou
        agentes = user.agentemembro_set.filter(
            is_administrador=True).values_list('agente__pk', flat=True)
        return self.user_add_id == user.id or self.agente_id in agentes

    def get_create_url(self):
        return self.__class__._get_create_url()

    @property
    def tipo(self):
        return self.get_child().__class__._tipo()

    @property
    def app_model(self):
        return 'acao.{}'.format(self.get_child().__class__.__name__)

    @property
    def agente_add(self):
        return self.agente if self.agente else self.user_add

    def is_member(self, user):
        return not user.is_anonymous() and self.membros_ativos().filter(user=user).count() >= 1

    def is_administrador(self, user):
        return not user.is_anonymous() and self.membros_ativos().filter(user=user, is_administrador=True).count() >= 1

    def can_change_gallery(self, user):
        return any([self.is_member(user), self.is_administrador(user)])

    def add_member(self, user, is_administrador=False, user_add=None, **kwargs):
        acaomembro = AcaoMembro(
            user=user, is_administrador=is_administrador, **kwargs)

        if user_add:
            acaomembro.user_add = user_add
            acaomembro.user_upd = user_add
        else:
            acaomembro.user_add = user
            acaomembro.user_upd = user

        self.acaomembro_set.add(acaomembro, bulk=False)

    def remove_member(self, user):
        if self.acaomembro_set.filter(is_administrador=True).exclude(user=user).count() >= 1:
            self.acaomembro_set.filter(user=user).delete()

    def add_vinculo(self, agente, user_add):
        vinculo = AcaoAgenteVinculo(
            agente=agente, user_add=user_add, user_upd=user_add)
        self.acaoagentevinculo_set.add(vinculo, bulk=False)

        return True

    def remove_vinculo(self, agente):
        self.acaoagentevinculo_set.filter(agente=agente).delete()

    def has_vinculo(self, agente):
        return self.acaoagentevinculo_set.filter(agente=agente).count() >= 1

    def membros_ativos(self):
        return self.acaomembro_set.filter(user__is_active=True)

    def send_new_member_email(self, user):
        from django.core.mail import send_mail

        current_site = Site.objects.get_current()
        subject = u'[Cultura Educa] - Novo membro em ação %s' % self.nome
        template = get_template('acao/email/email_novo_acaomembro.html')

        email = template.render({
            'site_name': current_site.name,
            'domain': current_site.domain,
            'protocol': u'https',
            'acao': self.get_child(),
            'user': user,
        })

        send_emails = self.acaomembro_set.filter(
            is_administrador=True).values_list('user__email', flat=True)

        return send_mail(subject, email, settings.DEFAULT_FROM_EMAIL, send_emails, html_message=email)

    @property
    def locais_acoes(self):
        if not hasattr(self, '_locais'):
            locais_diretos_pk = list(
                self.locais_diretos.values_list('pk', flat=True))
            locais_atividades_pk = []
            if hasattr(self, 'atividades'):
                for atividade in self.atividades.all():
                    locais_atividades_pk.extend(
                        atividade.locais_diretos.filter(
                            local__point__isnull=False
                        ).values_list('pk', flat=True)
                    )
            locais_pks = set(locais_diretos_pk + locais_atividades_pk)
            setattr(self, '_locais', Local.objects.filter(
                locais_acoes__pk__in=locais_pks))
        return getattr(self, '_locais')

    @property
    def transformed_locais(self):
        """Transforma ponto para o SRID do mapa, utilizado na aba rede."""
        locais = self.locais_acoes
        locais.transform(3857)
        return locais

    def setores_censitarios_entorno(self, raio=1):
        if not hasattr(self, '_setores_censitarios_entorno'):
            from itertools import chain
            from ibge.models import SetorCensitario
            setores_pk = list(chain(*[
                SetorCensitario.objects.entorno(
                    local.point.y, local.point.x, raio
                ).values_list('pk', flat=True) for local in self.locais_acoes.filter(point__isnull=False)
            ]))
            setattr(self, '_setores_censitarios_entorno',
                    SetorCensitario.objects.filter(pk__in=set(setores_pk)))

        return getattr(self, '_setores_censitarios_entorno')

    @property
    def locais_multipoint(self):
        return MultiPoint(
            *self.locais_acoes.transform(srid_out=3857, geom_field='point').values_list('point', flat=True)
        )

    @property
    def setores_censitarios_entorno_polygon(self):
        from django.contrib.gis.db.models import Union
        return self.setores_censitarios_entorno().transform(
            srid_out=3857,
            geom_field='point'
        ).aggregate(area=Union('geom'))['area']

    @property
    def agentes(self):
        pks = self.acaoagentevinculo_set.values_list('agente__pk', flat=True)
        return Agente.objects.filter(pk__in=pks)

    @property
    def rede_acoes(self):
        pks = list(self.acaoagentevinculo_set.values_list(
            'agente__pk', flat=True))
        return Acao.objects.filter(agente__pk__in=pks).annotate(
            acao_outro_agente=Case(
                When(Q(agente__pk__in=pks), then=Value(True)),
                default=Value(False),
                distinct=True,
                output_field=models.BooleanField()
            )
        )

    @property
    def rede_projetos(self):
        return self.rede_acoes.filter(projeto__isnull=False)

    @property
    def rede_atividades(self):
        return self.rede_acoes.filter(atividade__isnull=False)


class Local(EnderecoBase):
    local_nome = models.CharField(
        u'Local',
        max_length=120,
        null=True,
        blank=True
    )
    objects = models.GeoManager()

    def __unicode__(self):
        return u'%s' % (
            self.local_nome if self.local_nome else u'Local #%s' % self.pk
        )

    def get_absolute_url(self):
        return reverse('acaolocal_detail', args=(self.pk,))

    @property
    def local(self):
        return u'%s' % self.local_nome

    @property
    def lista_url(self):
        return reverse_lazy('lista_acaolocal')

    def get_search_url(self):
        return reverse('local_search')

    @property
    def target_url(self):
        return self.get_absolute_url()

    def equipamentos_entorno(self, raio=1):
        return equipamentos_entorno(self, raio=raio, geom_field='point')


class LocalAcao(models.Model):
    acao = models.ForeignKey(Acao, related_name=u'locais_diretos')
    local = models.ForeignKey(Local, related_name=u'locais_acoes')

    def user_can_delete(self, user):
        return self.acao.can_edit(user)


def localacao_postdelete_signal(sender, instance, **kwargs):
    layer_name = u'acao_atividade' if isinstance(
        instance.acao.get_child(), Atividade) else u'acao_projeto'
    clean_tilestache_cache(point=instance.local.point, layer=layer_name)

axis/acao/templates/acao/acao_remocao_modal.html
<div aria-hidden="true" aria-labelledby="modalTitleDeleteAcaoModal" class="reveal-modal" data-reveal="" id="{% if id %}{{ id }}{% else %}deleteAcaoModal{% endif %}" role="dialog">
    <h2 id="modalTitleDeleteAcaoModal">Remover {% if acao_tipo %}{{ acao_tipo }}{% else %}{{ acao.tipo|lower }}{% endif %}</h2>
    <p class="lead">Tem certeza que deseja remover essa ação <b>definitivamente</b>?</p>
    <a class="alert button right remove-atividade-link" href="{% if acao %}{% url 'generic_delete' acao.app_model acao.pk %}?next={% url 'profile_detail' %}#fndtn-panel-acoes{% endif %}">Continuar e remover</a>
    <a aria-label="Close" class="close-reveal-modal">&times;</a>
</div>

axis/acao/templates/acao/acao_tab.html
{% include "acao/acao_remocao_modal.html" with acao_tipo="ação" id="remover_atividade_modal" %}

<div class="row">
    <div class="medium-12 columns">
        <table role="grid" width="100%">
            <tbody>
                <tr>
                    <th colspan="{% if request.user.pk == agente.pk or is_administrador %}3{% else %}2{% endif %}" style="padding-right:0;">
                        <h5>
                            Projetos
                            {% if is_administrador %}
                                {% if is_pessoafisica %}
                                <a href="{% url 'projeto_create' %}" class="button secondary small right" style="margin-right: 0.5625rem;"><i class="fa fa-plus"></i> Cadastrar novo projeto</a>
                                {% else %}
                                <a href="{% url 'projeto_create' agente_pk=agente.pk %}" class="button secondary small right" style="margin-right: 0.5625rem;"><i class="fa fa-plus"></i> Cadastrar novo projeto</a>
                                {% endif %}
                             {% endif %}
                        </h5>
                    </th>
                </tr>
            {% for projeto in agente.projetos %}
            <tr class="acao">
                <td>
                    <a href="{{ projeto.get_absolute_url }}">{{ projeto.local|default:"Não Informado" }} </a><br>
                    {% if projeto.propositor_tipo == projeto.PROPOSITOR_TIPO.OUTROS %}
                    <strong>Propositor: </strong>({{ projeto.propositor_outro|default:"Não Informado" }})<br>
                    {% else %}
                    <strong>Propositor: </strong>{{ projeto.get_propositor_tipo_display }} - ({{ projeto.propositor.nome|default:"Não Informado" }})<br>                   
                    {% endif %}
                    <strong>Temas: </strong>
                    {% for tema in projeto.temas.all%}
                        {{ tema }}, 
                    {% empty%}
                        "Não Informado"
                    {% endfor %}
                </td>
                <td>
                    <div class="right">
                        <strong>Membros Ativos: </strong>{{ projeto.membros_ativos.count|default:"Não Informado" }}<br>
                        <strong>Início: </strong>{{ projeto.inicio|date:"d/m/Y"|default:"N/I" }}<br>
                        <strong>Fim: </strong>{{ projeto.fim|date:"d/m/Y"|default:"N/I" }}</td>
                    </div>
                </td>
                {% if request.user.pk == agente.pk or is_administrador %}
                <td>
                    <div class="right" style="line-height: 75px;">
                        <a href="#" data-href="{% url 'generic_delete' projeto.app_model projeto.pk %}?next={{ request.path }}" class="button tiny alert noafter removerAcaoBtn" style="display: inline-block;"><i class="fa fa-times"></i> Remover</a>
                    </div>
                </td>
                {% endif %}
            {% empty %}
                <tr>
                    <td colspan="3">Nenhum projeto registrado</td>
                </tr>
            {% endfor%}
            </tbody>
        </table>
    </div>
    <div class="medium-12 columns">
        <table role="grid" width="100%">
            <tbody>
                <tr>
                    <th colspan="{% if request.user.pk == agente.pk or is_administrador %}3{% else %}2{% endif %}" style="padding-right:0;">
                        <h5>
                            Atividades
                             {% if is_administrador %}
                                {% if is_pessoafisica %}
                                <a href="{% url 'atividade_create' %}" class="button secondary small right" style="margin-right: 0.5625rem;"><i class="fa fa-plus"></i> Cadastrar nova atividade</a>
                                {% else %}
                                <a href="{% url 'atividade_create' agente_pk=agente.pk %}" class="button secondary small right" style="margin-right: 0.5625rem;"><i class="fa fa-plus"></i> Cadastrar nova atividade</a>
                                {% endif %}
                             {% endif %}
                        </h5>
                    </th>
                </tr>
            {% for atividade in agente.atividades %}
            <tr class="acao">
                <td>
                    <a href="{{ atividade.get_absolute_url }}">{{ atividade.local|default:"Não Informado" }} </a><br>
                    
                        <strong>Formato da Atividade: </strong>
                        {% if atividade.formato == "Outro"%}
                        {{ atividade.formato_outro|default:"Não Informado"}}
                        {% else %}
                        {{ atividade.formato|default:"Não Informado" }}
                        {% endif %}
                    
                    <br>                   
                    
                        <strong>Temas: </strong>
                        {% for tema in atividade.temas.all%}
                            {{ tema }}, 
                        {% empty%}
                            "Não Informado"
                        {% endfor %}
                    
                </td>
                <td>
                    <div class="right">
                        <strong>Membros Ativos: </strong>{{ atividade.membros_ativos.count|default:"Não Informado" }}<br>
                        <strong>Início: </strong>{{ atividade.inicio|date:"d/m/Y"|default:"Não Informado" }}<br>
                        <strong>Fim: </strong>{{ atividade.fim|date:"d/m/Y"|default:"Não Informado" }}</td>
                    </div>
                </td>
                {% if request.user.pk == agente.pk or is_administrador %}
                <td>
                    <div class="right" style="line-height: 75px;">
                        <a href="#" data-href="{% url 'generic_delete' atividade.app_model atividade.pk %}?next={{ request.path }}" class="button tiny alert noafter removerAcaoBtn" style="display: inline-block;"><i class="fa fa-times"></i> Remover</a>
                    </div>
                </td>
                {% endif %}
            {% empty %}
                <tr>
                    <td colspan="3">Nenhuma atividade registrado</td>
                </tr>
            {% endfor%}
            </tbody>
        </table>
    </div>
</div>

axis/acao/templates/acao/base_form.html
{% extends 'base.html' %}
{% load static l10n staticfiles foundation_filter %}

{% block titulo %}
  {% if form.instance.pk %}
    Editar {{ form.tipo|lower }}: {{ form.instance.nome }}
  {% else %}
    Novo(a) {{ form.tipo|lower }}
  {% endif %}
{% endblock titulo %}

{% block extra_css %}
{{ form.media.css }}
{% endblock %}

{% block extra_js %}
{{ form.media.js }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/3.17.1/ol.js" type="text/javascript"></script>
<script src="{% static 'js/form/formset.js' %}" type="text/javascript"></script>
<script src="{% static 'js/form/form_field_outros.js' %}" type="text/javascript"></script>
<script src="{% static 'js/map.js' %}?v=1" type="text/javascript"></script>
<script type="text/javascript">
$(function() {

  $("#financiamentos").on('change', 'select[name$="tipo"]', function() {

    var wrapper = $(this).parents('.wrapper');

    if ($(this).val() == '{{ FINACIAMENTO_OUTRO_VALUE }}') {
      $(".financiamento_outro", wrapper).slideDown('fast');
      $(".financiamento_empresa", wrapper).slideUp('fast');
      $(".financiamento_outro input", wrapper).prop('required', true);
      $(".financiamento_outro input", wrapper)[0].focus();
      $(".financiamento_empresa input", wrapper).prop('required', false);
    } else if ($(this).val() == '{{ FINACIAMENTO_EMPRESA_VALUE }}') {
      $(".financiamento_empresa", wrapper).slideDown('fast');
      $(".financiamento_outro", wrapper).slideUp('fast');
      $(".financiamento_empresa input", wrapper).prop('required', true);
      $(".financiamento_empresa input", wrapper)[0].focus();
      $(".financiamento_outro input", wrapper).prop('required', false);
    } else {
      $(".financiamento_empresa, .financiamento_outro", wrapper).hide();
      $(".financiamento_empresa input, .financiamento_outro input", wrapper).prop('required', false);
    }
  });

  $(".financiamento_empresa input, .financiamento_outro input, #id_acaomembro_vinculo_outro")
    .before('<i class="fa fa-asterisk fdt_required" style="" aria-hidden="true"></i>');

  $("#id_financiado").change(function() {
    if ($(this).is(":checked")) {
      $("#financiamentos").slideDown('fast', function() {
        $("#financiamentos select[name$='tipo']").prop('required', true);
        $("#financiamentos select[name$='tipo']").change();
      });
    } else {
      $("#financiamentos").slideUp('fast', function() {
        $("#financiamentos select[name$='tipo']").prop('required', false);
        $(".financiamento_empresa input, .financiamento_outro input").prop('required', false);
      });
    }
  });

  $("#id_financiado").change();

  $("#id_acaomembro_vinculo").change(function() {
    if ($(this).val() == '{{ VINCULO_OUTRO_VALUE }}') {
      $("#id_acaomembro_vinculo_outro").prop('required', true);
      $("#id_acaomembro_vinculo_outro").prop('disabled', false);
      $("#id_acaomembro_vinculo_outro")[0].focus();
    } else {
      $("#id_acaomembro_vinculo_outro").prop('required', false);
      $("#id_acaomembro_vinculo_outro").prop('disabled', true);
    }
  });

  $("#id_acaomembro_vinculo").change();

});
</script>

{% endblock extra_js %}

{% block content %}
<div aria-hidden="true" aria-labelledby="modalTitle" class="reveal-modal" data-reveal="" id="geoModalConfirm" role="dialog">
    <h2 id="modalTitle">Dados do Mapa</h2>
    <p class="lead">
        Você deseja Trocar os Dados do Formulário de Endereço pelos encontrados no Mapa?
    </p>
    <p>
        Rua:
        <span id="idConfirmStreet">
        </span>
    </p>
    <p>
        CEP:
        <span id="idConfirmPostcode">
        </span>
    </p>
    <p>
        Bairro:
        <span id="idConfirmSuburb">
        </span>
    </p>
    <p>
        Cidade:
        <span id="idConfirmCity">
        </span>
    </p>
    <p>
        <button class="secondary button success" href="#" id="btnConfirmGeo">Sim</button>
        <button class="secondary button" href="#" id="btnNotConfirmGeo">Não</button>
    </p>
    <a aria-label="Close" class="close-reveal-modal">
        ×
    </a>
</div>
<div class="columns medium-12 medium-centered">
   <div class="content-page">
       {% if form.instance.pk %}
       <h2>
           <small>
               Editar {{ form.tipo|lower }}:
           </small>
           {{ form.instance.nome }}
       </h2>
       {% else %}
       <h2>
          <small>{% block subtitle %}Novo(a) {{ form.tipo|lower }}{% endblock subtitle %}</small>
       </h2>
       {% endif %}
       {% block form %}{% endblock form %}
  </div>
</div>
{% endblock content %}

axis/acao/templates/acao/base_manage_locations.html
{% extends 'base.html' %}
{% load static l10n staticfiles foundation_filter %}

{% block titulo %}
  {% if form.instance.pk %}
    Editar {{ form.tipo|lower }}: {{ form.instance.nome }}
  {% else %}
    Novo(a) {{ form.tipo|lower }}
  {% endif %}
{% endblock titulo %}

{% block extra_css %}
{{ form.media.css }}
{% endblock %}

{% block extra_js %}
{{ form.media.js }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/3.17.1/ol.js" type="text/javascript"></script>
<script src="{% static 'js/form/formset.js' %}" type="text/javascript"></script>
<script src="{% static 'js/map.js' %}?v=1" type="text/javascript"></script>
<script type="text/javascript">
$(function() {

  $("#financiamentos").on('change', 'select[name$="tipo"]', function() {

    var wrapper = $(this).parents('.wrapper');

    if ($(this).val() == '{{ FINACIAMENTO_OUTRO_VALUE }}') {
      $(".financiamento_outro", wrapper).slideDown('fast');
      $(".financiamento_empresa", wrapper).slideUp('fast');
      $(".financiamento_outro input", wrapper).prop('required', true);
      $(".financiamento_outro input", wrapper)[0].focus();
      $(".financiamento_empresa input", wrapper).prop('required', false);
    } else if ($(this).val() == '{{ FINACIAMENTO_EMPRESA_VALUE }}') {
      $(".financiamento_empresa", wrapper).slideDown('fast');
      $(".financiamento_outro", wrapper).slideUp('fast');
      $(".financiamento_empresa input", wrapper).prop('required', true);
      $(".financiamento_empresa input", wrapper)[0].focus();
      $(".financiamento_outro input", wrapper).prop('required', false);
    } else {
      $(".financiamento_empresa, .financiamento_outro", wrapper).hide();
      $(".financiamento_empresa input, .financiamento_outro input", wrapper).prop('required', false);
    }
  });

  $(".financiamento_empresa input, .financiamento_outro input")
    .before('<i class="fa fa-asterisk fdt_required" style="" aria-hidden="true"></i>');

  $("#id_financiado").change(function() {
    if ($(this).is(":checked")) {
      $("#financiamentos").slideDown('fast', function() {
        $("#financiamentos select[name$='tipo']").prop('required', true);
        $("#financiamentos select[name$='tipo']").change();
      });
    } else {
      $("#financiamentos").slideUp('fast', function() {
        $("#financiamentos select[name$='tipo']").prop('required', false);
        $(".financiamento_empresa input, .financiamento_outro input").prop('required', false);
      });
    }
  });

  $("#id_financiado").change();
});
</script>

{% endblock extra_js %}

{% block content %}
<div aria-hidden="true" aria-labelledby="modalTitle" class="reveal-modal" data-reveal="" id="geoModalConfirm" role="dialog">
    <h2 id="modalTitle">Dados do Mapa</h2>
    <p class="lead">
        Você deseja Trocar os Dados do Formulário de Endereço pelos encontrados no Mapa?
    </p>
    <p>
        Rua:
        <span id="idConfirmStreet">
        </span>
    </p>
    <p>
        CEP:
        <span id="idConfirmPostcode">
        </span>
    </p>
    <p>
        Bairro:
        <span id="idConfirmSuburb">
        </span>
    </p>
    <p>
        Cidade:
        <span id="idConfirmCity">
        </span>
    </p>
    <p>
        <button class="secondary button success" href="#" id="btnConfirmGeo">Sim</button>
        <button class="secondary button" href="#" id="btnNotConfirmGeo">Não</button>
    </p>
    <a aria-label="Close" class="close-reveal-modal">
        ×
    </a>
</div>
<div class="columns medium-12 medium-centered">
   <div class="content-page">
       {% if form.instance.pk %}
       <h2>
           <small>
               Editar {{ form.tipo|lower }}:
           </small>
           {{ form.instance.nome }}
       </h2>
       {% else %}
       <h2>
           <small>
               Novo(a) {{ form.tipo|lower }}
           </small>
       </h2>
       {% endif %}
       {% block form %}{% endblock form %}
  </div>
</div>
{% endblock content %}